name: Static Site

on:
  schedule:
    - cron:  '0 0 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fetch the dynamic site
      run: |
        mkdir TRAVIS
        cd TRAVIS
        git clone https://github.com/bobby285271/static.bobby285271.top.git --depth=5
        wget --mirror --convert-links --adjust-extension --page-requisites --retry-connrefused --execute robots=off https://www.bobby285271.top || true
        cd www.bobby285271.top
        find ./ -type f -exec sed -i -e 's|https://www.bobby285271.top|https://static.bobby285271.top|g' {} \;
        find ./ -type f -exec sed -i -e 's|https://bobby285271.top|https://static.bobby285271.top|g' {} \;
        find ./ -type f -exec sed -i -e 's|http://www.bobby285271.top|https://static.bobby285271.top|g' {} \;
        find ./ -type f -exec sed -i -e 's|http://bobby285271.top|https://static.bobby285271.top|g' {} \;
        cd ../  
        cp static.bobby285271.top/README.md www.bobby285271.top/
        cp static.bobby285271.top/CNAME www.bobby285271.top/  
        cp -r static.bobby285271.top/.github www.bobby285271.top/
        rm -rf static.bobby285271.top/*
        mv www.bobby285271.top/* static.bobby285271.top/
        cd static.bobby285271.top
        rm -f archiso/dasyatis-autobuild-x86_64.iso
        git config user.email rjl931189261@126.com
        git config user.name "Bobby Rong"
        git add -A
        git commit -m "Site Update, $(date)"
        git push https://bobby285271:${codingpasswd}@github.com/bobby285271/static.bobby285271.top.git master
