name: Git repo mirroring for SCNUOJ
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE }}
        with:
          source-repo: 'git@github.com:SCNU-SoCoding/scnuoj.git'
          destination-repo: 'git@gitee.com:bobby285271/scnuoj.git'
          
